#!/usr/bin/env bash
# Configuring my domain zone so that the subdomain www points to a load balancer.

my_domain_config()
{
    local domain="$1"
    local subdomain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | \
    awk 'BEGIN { found=0 } 
         /ANSWER SECTION:/ { found=1; next } 
         found==1 && NF>1 { 
             subdomain_parts = split($1, sd, ".");
             print "The subdomain " sd[1] " is a " $4 " record and points to " $5;
             found=0
         }'
}

if [ $# -eq 2 ]
then
    my_domain_config "$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"
do
        my_domain_config "$1" "$subdomain"
    done
fi
