#!/usr/bin/env bash
# Configuring my Nginx server to make a redirection to another page. 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh - 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://theenduranceaneke.tech permanent;' /etc/nginx/sites-available/default
sudo service nginx start
