#!/usr/bin/env bash
# Script that debugs my nginx installation.
# Already existing nginx was deleted
# A new nginx was installed.

sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
