#!/usr/bin/env bash
# Script that debugs my nginx installation.
# Already existing nginx was deleted
# A new nginx was installed.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
