#!/usr/bin/env bash
# A script that displays Best School 10 times but Hi at the 9th itration using the while loop and if statement.

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
