#!/usr/bin/env bash
# A script that loops through 1 to 10 and:
# displays bad luck for the 4th loop iteration,
# displays good luck for the 8th loop iteration,
# displays Best School for the other iterations.
# Using the while loop and the if, elif and else statements.

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
