#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59.
# Using the while loop.

hr=0
while [ $hr -le 12 ]
do
	echo "Hour: $h"
	min=1
	while [ $min -lt 60 ]
	do
		echo $min
		(( min++ ))
	done
	(( hr++ ))
done
