#!/usr/bin/env bash
# Script that configures the nginx user to run nginx listening at port 8080

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
